# Generated by Django 5.0.4 on 2024-04-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_name_product_title_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
